### ISSUE TITLE
Not possible to import db2 / ojdbc driver in class path

### ISSUE THREAD

**Issue by chit786** [xebialabs/xl-docker-images#17]
Currently container fails to start for db2 and oracle jdbc driver since :  https://github.com/xebialabs/xl-docker-images/blob/d08feae34a052a4f64f543a875f189b80b49bea7/xl-release/8.5/resources/bin/run-in-container.sh#L22

![image](https://user-images.githubusercontent.com/18376182/54565460-a2818a80-49ce-11e9-8b38-92fdf264bf38.png)

Can we provide another environment variable where user can allow his own jdbc drivers and not stopping docker containers?

**Comment by chit786** [comment]
cc @eltonkevani  git blame mentions you :)

**Comment by eltonkevani** [comment]
yeah that is not supported yet. has to be added to https://github.com/xebialabs/xl-docker-images/blob/master/templates/resources/common/bin/db-drivers.sh

**Comment by chit786** [comment]
but can we pls add a possibility to allow me to give my own jdbc driver. I have my jdbc driver but can not override it since container exits https://github.com/xebialabs/xl-docker-images/blob/d08feae34a052a4f64f543a875f189b80b49bea7/xl-release/8.5/resources/bin/run-in-container.sh#L23 :((
