### ISSUE TITLE
docker-compose.yaml file missing

### ISSUE THREAD

**Issue by netwolfuk** [xebialabs/xl-docker-images#33]
I am looking for the files referenced here:
https://docs.xebialabs.com/v.9.0/xl-release/how-to/getting-started-with-xl-docker-containers/

I found them here: 
https://github.com/xebialabs/xl-docker-images/blob/8.5/8.1/docker-compose.yaml

However, the docs need updating (and the compose file needs updating to 9.0)

**Comment by ielshal** [comment]
Thank you @netwolfuk for reporting this and sorry for late reply .. We added this as an example which is not connected to specific version .. but i agree i just fixed this in both our repo and documentation to avoid any confusion here.
